.github/scripts/assign-reviewer.ts, .github/workflows/pr-init.yml, .github/workflows/review-on-label.yml, package-lock.json, package.json, tsconfig.actions.json
이슈 번호 없음
> 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)
- Assignee, Reviewer 선정 자동화 및 리뷰요청 라벨 교체시 Slack 리뷰 알림
>
> 추가하려는 기능에 대해 간결하게 설명해주세요
=> chore: 자동화 설정

package-lock.json, package.json
중복제거랑 script dev설정에 --turbo 제거
=> chore: package.json 중복제거

README.md, apps/user/package.json, package.json
_모노레포에서 vitest 설정하는 부분이 누락되어 테스트가 불가능합니다_
루트 경로에서 pnpm test 시  vitest가 동작하도록 수정했습니다. 
-   [x] vitest 명령어 추가
| 작업 |
| ---  |
|     ![image](https://github.com/user-attachments/assets/a56ecb90-0d6d-45d6-812c-db70dbc75c46)     |
>
=> fix: monorepo vitest 설정

.github/scripts/assign-reviewer.ts
- slack 리뷰어 알림 DM시 자신에게 보내는 경우 DM창이 열려있지 않으면 오류 발생
- DM 전송하기 전 DM창을 임의로 열어줌
-   [ ] TODO
-   [ ] TODO
-   [ ] TODO
| 전  | 후  |
| --- | --- |
|     |     |
>
=> fix: slack self dm시 오류 수정

.husky/pre-commit
#52 
pnpm lint-staged가 아니라 커밋 시 오류가 발생한다는 이슈가 있어서 수정하였습니다. 
-   [x] husky 명령어 수정
| 전  | 후  |
| --- | --- |
|     |     |
>
npx와 유사한 pnpm의 dlx 명령어를 통해서 실행하도록 적용하였습니다. 
설정 변경으로 X
=> fix: husky 설정 변경 

apps/user/src/app/layout.tsx, apps/user/src/styles/reset.css.ts, apps/user/src/styles/theme.css.ts
이슈 번호 없음 
초기 Theme 색상이나 reset css를 추가했습니다. 
Theme의 경우 피그마 기준으로 작성했습니다. 
-   [x] theme 추가
-   [x] reset css 추가
| 전  | 후  |
| --- | --- |
|     |     |
>
reset css가 좀 부실한 느낌도 있고 폰트 등은 적용하지 않은 상태입니다. 
하지만 중간에 해당 요소가 들어가게 된다면 협업 시 불편함이 있을 것 같아서 빠르게 생각나는 부분만 우선 적용하였습니다. 
추가 스타일은 피드백 부탁드립니다!
=> feat: global style 세팅

apps/user/src/__test__/hooks/useSearchRecommendations.test.ts, apps/user/src/hooks/useSearchRecommendations.ts, apps/user/src/mocks/handlers/index.ts, apps/user/src/mocks/handlers/recommendations/index.ts, apps/user/src/mocks/handlers/suggestions/index.ts
#23
- 추천어 리스트 MSW 핸들러 구현
- 추천어 리스트 요청 Hook (`useSearchSuggestions`) 구현
- 추천어 리스트 Hook 테스트 코드 작성
- 추천어 리스트 정렬 및 중복 제거
-   [x] `/recommendations?searchTerm=` 요청을 처리하는 mock 핸들러 구현
-   [x] `useSearchRecommendations` Hook 구현 (fetch + debounce + concurrency 처리)
-   [x] `useSearchRecommendations` 테스트 코드 작성 및 동시성 테스트
-   [x] 추천어 중복 제거
- 리뷰 주셨던 부분 정리 해서 추가 논의와 공유가 필요한 사항만 정리했습니다.
- 
1. 대소문자 구분 없이 검색이 가능해야 한다. (`"Nike"` → `"nike"`와 동일하게 처리)    
→ 서버에서 처리    
2. 검색어에 특수문자(`@`, `!`, `#`)가 포함되었을 경우에도 앱이 깨지지 않아야 한다.
3. 검색어 자동완성 리스트가 너무 많을 경우, **상위 N개만 보여줘야 한다.**    
→ 몇개로 고려를 하는게 좋을지 상의가 필요할 것 같은데…    
4. 매우 긴 검색어(100자 이상)를 입력해도 앱이 **깨지지 않고 반응**해야 한다.    
→ 검색할때 input창에서 제어를 주는게 좋을 것 같습니다.
5. 한글 자음만 입력했을 때(`ㅎㄱ`)도 초성 검색이 가능해야 한다. 
→ 초성 검색 관련 로직은 백엔드에서 처리하여 내려주는게 성능면에서 맞다고 생각합니다.
- 테스트를 위해서 화면만 구현했기에 해당 …
=> feat: 검색어 상태 + 추천어 관리 + 필터링

.github/workflows/pr-template-cleanup.yml
PR이 열리거나 수정될 때마다 실행되는 워크플로우를 추가했습니다.
- 10분 후에 PR 설명을 검토하여 내용이 없는 섹션은 자동으로 삭제합니다.
- 내용이 있는 섹션에서는 > 로 시작하는 가이드 코멘트를 자동으로 제거합니다.
-   [ ] TODO
-   [ ] TODO
-   [ ] TODO
| 전  | 후  |
| --- | --- |
|     |     |
>
=> feat: add PR template cleanup workflow

.github/workflows/owner-ci-cd.yml, .github/workflows/user-ci-cd.yml
이슈 없음
개발 버전으로 배포 시 프로덕션 모드로 배포되는 것 같아서 코드 수정 
-   [x] 배포 설정 수정
| 전  | 후  |
| --- | --- |
|     |     |
>
`--prod` 설정이 추가되어 있어 `environment`를 `dev`로 설정해도 prod 모드로 배포되는 것 같아서 변경해봤습니다. 
확인 부탁드립니당!
=> chore: 개발 환경 배포 수정

.github/workflows/owner-ci-cd.yml, .github/workflows/user-ci-cd.yml
테스트 커버리지 action 설정을 수정했습니다.
- user app 은 경고만 주고, 머지를 막지는 않음
- owner app 은 커버리지 아예 삭제 (불필요하다고 판단)
-   [ ] TODO
-   [ ] TODO
-   [ ] TODO
| 전  | 후  |
| --- | --- |
|     |     |
>
=> chore: 테스트 커버리지 관련 액션 수정

apps/user/src/hooks/useAutoComplete/index.ts, apps/user/src/hooks/useAutoComplete/useAutoComplete.test.ts, apps/user/src/hooks/useGeolocation/index.ts, apps/user/src/stores/index.test.ts, apps/user/src/stores/index.ts, apps/user/src/stores/searchHistoryStore/index.ts, apps/user/src/stores/userLocationStore/index.ts
api 요청시 위도, 경도값이 필수값이라 전역 변수로 변경했습니다.
- sessionStorage 에 저장하도록 수정함
[기타]
- 기존 search 관련 스토리지 파일 컨벤션에 맞게 수정
-   [ ] TODO
-   [ ] TODO
-   [ ] TODO
| 전  | 후  |
| --- | --- |
|     |     |
>
=> feat: 사용자 location 정보 전역변수로 변경

apps/user/package.json
- 환경변수는 노션을 참고해주세용
| 전  | 후  |
| --- | --- |
|     |     |
>
=> chore: Prod용 script 추가

apps/user/src/app/(bottomNav)/mypage/page.tsx
로그인이 안된 화면에서도 로그아웃/회원탈퇴 UI가 있어서 수정하였습니다. 
-   [x] 화면 조건식 추가
| 전  | 후  |
| --- | --- |
|     |     |
>
=> fix: mypage 로그인 정보에 따른 필터링

apps/owner/src/apis/client.ts, apps/owner/src/apis/ssr/file-upload/index.ts, apps/owner/src/apis/ssr/product/index.ts, apps/owner/src/apis/ssr/review/index.ts, apps/owner/src/apis/ssr/stores/index.ts
-   [ ] TODO
-   [ ] TODO
-   [ ] TODO
| 전  | 후  |
| --- | --- |
|     |     |
>
=> fix/owner api 설정 수정 (product 쪽만 baseUrl이 달라서 그에 맞게 처리함)

apps/owner/src/apis/client.ts, apps/owner/src/apis/ssr/product/index.ts
상품쪽도 api/v1 prefix 붙으면서 deprecated됨
-   [ ] TODO
-   [ ] TODO
-   [ ] TODO
| 전  | 후  |
| --- | --- |
|     |     |
>
=> fix: product api instance deprecated

apps/owner/src/components/common/order-sse-listener.tsx, apps/owner/src/components/common/sse-status-indicator.tsx
로그인 전이나 로그인 페이지에서는 SSE 연결을 차단하고, 상태 표시기에 연결 해제 상태를 반영햇습니다.
-   [ ] TODO
-   [ ] TODO
-   [ ] TODO
| 전  | 후  |
| --- | --- |
|     |     |
>
=> fix: 비로그인시 sse 연결 시도를 하지 않음

apps/owner/package.json, apps/owner/src/app/product-management/[id]/page.tsx, apps/owner/src/app/product-management/new/page.tsx, apps/owner/src/app/product-management/page.tsx, apps/owner/src/types/file-upload.ts, apps/owner/src/types/product.ts, pnpm-lock.yaml
#176 
-   [ ] TODO
-   [ ] TODO
-   [ ] TODO
| 전  | 후  |
| --- | --- |
|     |     |
>
=> 운영자 상품 - api 수정 및 s3 uploader 코드 개선

apps/user/next.config.ts, apps/user/src/app/(topNav)/stores/[id]/products/page.tsx
storeId = 1로 하면 products 나옴
-   [ ] TODO
-   [ ] TODO
-   [ ] TODO
| 전  | 후  |
| --- | --- |
|     |     |
>
=> fix: products csr로 변경

apps/owner/src/app/product-management/[id]/page.tsx, apps/owner/src/app/product-management/new/page.tsx, apps/owner/src/app/product-management/page.tsx, apps/owner/src/app/reviews/page.tsx, apps/owner/src/utils/imageUpload.ts, biome.json
> ex) [#32](https://github.com/InnerCircle-ICD3/o2o-fe/issues/32)
> owner 상품, 리뷰페이지에 하드코딩을 제거하고 이미지 s3업로드 코드를 추가하였습니다
-   [ ] TODO
-   [ ] TODO
-   [ ] TODO
| 전  | 후  |
| --- | --- |
|     |     |
>
=> Fix/owner product review 하드코딩 제거

apps/user/src/app/(bottomNav)/subscribes/page.tsx, apps/user/src/app/orders/[id]/success/page.tsx, apps/user/src/components/common/orderInfo/index.tsx, apps/user/src/components/ui/storeList/storeCard/index.tsx, apps/user/src/components/ui/storeList/storeListContainer/index.tsx, apps/user/src/components/ui/storesDetail/storesInfo/index.tsx, apps/user/src/components/ui/storesDetail/storesInfo/storesInfo.css.ts, apps/user/src/components/ui/subscribe/subscribeItem/index.tsx, apps/user/src/components/ui/subscribe/subscribeItem/subscribeItem.test.tsx, apps/user/src/hooks/useGeolocation/index.ts, apps/user/src/hooks/useGeolocation/useGeolocation.test.ts
텍스트가 조금 깨지거나 이미지가 이상한 부분 수정했습니다. 
-   [x] 디테일 수정
| 전  | 후  |
| --- | --- |
|     |     |
>
=> fix: 디테일 수정

apps/user/src/app/(bottomNav)/subscribes/page.tsx, apps/user/src/app/orders/[id]/success/page.tsx, apps/user/src/components/common/orderInfo/index.tsx, apps/user/src/components/common/products/index.tsx, apps/user/src/components/common/products/product.test.tsx, apps/user/src/components/ui/storeList/storeCard/index.tsx, apps/user/src/components/ui/storeList/storeListContainer/index.tsx, apps/user/src/components/ui/storesDetail/productBottomSheet/productBottomSheet.test.tsx, apps/user/src/components/ui/storesDetail/select/select.test.tsx, apps/user/src/components/ui/storesDetail/storesInfo/index.tsx, apps/user/src/components/ui/storesDetail/storesInfo/storesInfo.css.ts, apps/user/src/components/ui/subscribe/subscribeItem/index.tsx, apps/user/src/components/ui/subscribe/subscribeItem/subscribeItem.test.tsx, apps/user/src/hooks/api/useSubscribeList/index.ts, apps/user/src/hooks/useGeolocation/index.ts, apps/user/src/hooks/useGeolocation/useGeolocation.test.ts, apps/user/src/types/apis/stores.type.ts
-   [ ] TODO
-   [ ] TODO
-   [ ] TODO
| 전  | 후  |
| --- | --- |
|     |     |
>
=> 2025-06-20 dev > main 5차

apps/user/src/app/(bottomNav)/subscribes/page.tsx, apps/user/src/app/(topNav)/review/[id]/page.tsx, apps/user/src/app/orders/[id]/success/page.tsx, apps/user/src/components/common/orderInfo/index.tsx, apps/user/src/components/common/products/index.tsx, apps/user/src/components/common/products/product.test.tsx, apps/user/src/components/common/products/products.css.ts, apps/user/src/components/ui/locations/myLocation/index.tsx, apps/user/src/components/ui/locations/rangeSelector/rangeSelector.test.tsx, apps/user/src/components/ui/review/rating.tsx, apps/user/src/components/ui/storeList/storeCard/index.tsx, apps/user/src/components/ui/storeList/storeListContainer/index.tsx, apps/user/src/components/ui/storesDetail/productBottomSheet/productBottomSheet.test.tsx, apps/user/src/components/ui/storesDetail/select/select.test.tsx, apps/user/src/components/ui/storesDetail/storesInfo/index.tsx, apps/user/src/components/ui/storesDetail/storesInfo/storesInfo.css.ts, apps/user/src/components/ui/subscribe/subscribeItem/index.tsx, apps/user/src/components/ui/subscribe/subscribeItem/subscribeItem.test.tsx, apps/user/src/hooks/api/useSubscribeList/index.ts, apps/user/src/hooks/useGeolocation/index.ts, apps/user/src/hooks/useGeolocation/useGeolocation.test.ts, apps/user/src/types/apis/stores.type.ts
-   [ ] TODO
-   [ ] TODO
-   [ ] TODO
| 전  | 후  |
| --- | --- |
|     |     |
>
=> 2025-06-20 dev > main 6차 

apps/user/src/components/ui/my-orders/orderItem/index.tsx
-   [ ] TODO
-   [ ] TODO
-   [ ] TODO
| 전  | 후  |
| --- | --- |
|     |     |
>
=> 2025-06-20 dev > main 7차

apps/user/src/components/ui/filterTab/pickUpTimeFilter/index.tsx, apps/user/src/components/ui/my-orders/orderItem/index.tsx, apps/user/src/components/ui/storeList/storeListContainer/index.tsx
-   [ ] TODO
-   [ ] TODO
-   [ ] TODO
| 전  | 후  |
| --- | --- |
|     |     |
>
=> 2025-06-21 dev > main 1차

apps/owner/src/app/layout.tsx
-   [ ] TODO
-   [ ] TODO
-   [ ] TODO
| 전  | 후  |
| --- | --- |
|     |     |
>
=> fix: sse 패널개발환경에서만 보임

apps/user/src/components/common/orderInfo/index.tsx
-   [ ] TODO
-   [ ] TODO
-   [ ] TODO
| 전  | 후  |
| --- | --- |
|     |     |
>
=> fix: 주문 시 totalPrice 수량 포함 계산

apps/owner/src/components/common/order-sse-listener.tsx
-   [ ] TODO
-   [ ] TODO
-   [ ] TODO
| 전  | 후  |
| --- | --- |
|     |     |
>
=> fix: 도메인 수정..

apps/owner/src/components/common/order-sse-listener.tsx
-   [ ] TODO
-   [ ] TODO
-   [ ] TODO
| 전  | 후  |
| --- | --- |
|     |     |
>
=> fix: 도메인 수정.. (#219)

apps/owner/src/components/common/order-sse-listener.tsx
-   [ ] TODO
-   [ ] TODO
-   [ ] TODO
| 전  | 후  |
| --- | --- |
|     |     |
>
=> dev > main 재배포

apps/user/src/components/ui/filterTab/pickUpTimeFilter/index.tsx
픽업 시간 초기화 시 모달에 선택이 남아있는 이슈 수정
https://innercircledevcourse3.slack.com/archives/C08P42G0Q8J/p1750677053366549
-   [ ] TODO
-   [ ] TODO
-   [ ] TODO
| 전  | 후  |
| --- | --- |
|     |     |
>
=> fix: pickup filter 리셋

apps/user/src/hooks/api/useProduct/index.ts
상품 상세 갱신하는 쿼리로 수정 
https://innercircledevcourse3.slack.com/archives/C08P42G0Q8J/p1750679644288419
-   [ ] TODO
-   [ ] TODO
-   [ ] TODO
| 전  | 후  |
| --- | --- |
|     |     |
>
=> fix: subscribe 새로고침 시 갱신되는 이슈
